### PR TITLE
Adding frame counters and bus load measurement for CAN

### PR DESCRIPTION
**Pull request by agomez08**
Changes by @keprt 
-Updated to 2018.
-Added an extra channel that keeps count on the received frames for each port.

My changes:
-Added extra channel only for CAN ports that reports the estimated percentage of bus usage.
-Measurement period is configurable for each port.
-This feature can be disabled for each port. Enabled by default.

How this was tested:
-Deployed SDF with 2 CAN ports into Linux_x64 cRIO.
-Measured bus load for different conditions involving CAN 2.0, CAN FD and CAN FD+BRS. 
-Results are very similar (+/-1%) to what is reported by XNET Bus Monitor.

### CODE REVIEW

**Comment by czokubik** [comment]
I cannot test the code up and running as I don't have access to the HW now, but the driver VI looks good.
I think is time to increment the CD version as it introduces new features (also readme should describe the new features). I'd also implement version update VI as a part of the OnLoad action VIs to add for new channels.

"\System Explorer\Port.vi" - the "Bus.Load.Period.ms" control should be in "System" design (not "modern") and it deserves for some documentation (control description). Both "Disable Bus Load" and "Bus.Load.Period.ms" controls should be horizontally aligned with other controls on the FP.

Overall, very good job!

**Comment by keprt** [comment]
@agomez08 would you implement @czokubik proposal?

**Comment by agomez08** [comment]
Hi @czokubik @keprt 
Thanks for the feedback! I will update with the changes you recommended between today and tomorrow.

**Comment by agomez08** [comment]
@czokubik @keprt 

I implemented the next changes:

-Version 2.0.0 is written from Version Manager.vi which is called as a part of ActionVIOnLoad.
-Version Manager also upgrades to 2.0.0 in case loaded version is 1.0.0 by creating the new channels.
-Changed period control to System design and added tip strip and documentation for this control.
-Aligned "Disable Bus Load" and "Bus.Load.Period.ms" with other controls.

I tested the changes by creating an SDF using version 1.0.0 with CAN, LIN and FlexRay ports. After the upgrade to 2.0.0, the new channels were added for each of these ports.

Please let me know if you have more observations. Feel free to integrate other small changes that you consider appropriate in case I missed something. 

Thanks!

**Comment by czokubik** [comment]
@agomez08 
Very well! Version bump VIs seems to be ok, but before merging your pull request, please update the CD version in the "Custom Device NI-XNET Monitor.xml" to 2.0.0 . In future versions we should consider moving hard-coded constants for channel names and descriptions to the global variable "NI-XNET Monitor Shared.lvlib:Constants.vi" to prevent typos and be ready for localization ...

**Comment by agomez08** [comment]
@czokubik 
I modified the XML to have the 2.0.0 version. 
I agree that moving channel names and descriptions to global constants would be a good idea for the next major release.
Thanks!

**Pull request merged**
